#!/bin/sh
rm -rf 10.101.115.211

wget -m -np "http://10.101.115.211/j/source/ieee754-verilog/src"
wget -m -np "http://10.101.115.211/j/source/ieee754-verilog/test"

find . -name "*index.html*" | xargs rm -v

mkdir -p bin

echo 'Compiling & Running'
vcs +v2k -q src/ieee.v src/ieee_adder.v test/testbench.v -R > bin/simulation.out

##cat bin/simulation.out
##exit

gcc test/test_simulation.c -o bin/test_simulation
bin/test_simulation < bin/simulation.out

vcs +v2k -q src/ieee.v src/ieee_adder.v test/autogenerated/testbench.v -R > bin/simulation.out
bin/test_simulation < bin/simulation.out

