////////////////////////////////////////////
//                                        //
//  THIS FILE IS AUTOMATICALLY GENERATED  //
//     BY generate.py, DO NOT EDIT!       //
//                                        //
////////////////////////////////////////////
`include "defines.v"
module emir(A,B,clock_in,Z,Y);
	input  A;
	input  B;
	input  clock_in;
	output  Z;
	output  Y;
	/////////////
	// STAGE 1 //
	/////////////
	//Outputs of module 'prep' with instance 'prep'
	wire  s1o_C;
	//Outputs of module 'end' with instance 'end'
	wire  s1o_Y;
	wire  s1o_Z;
	//Calling instance 'prep'
	emir_prep S1_emir_prep (
		/*input*/.A(A),
		/*input*/.B(B),
		/*output*/.C(s1o_C)
	);
	//Calling instance 'end'
	emir_end S1_emir_end (
		/*input*/.C(s1o_C),
		/*output*/.Y(s1o_Y),
		/*output*/.Z(s1o_Z)
	);
	//Connect stage 1 to pipeline output
	assign Y = s1o_Y;
	assign Z = s1o_Z;
endmodule
