///////////////////////////////////////////////////////////////////////
//                                                                   //
// THIS FILE IS AUTOMATICALLY GENERATED BY generate.py, DO NOT EDIT! //
//                                                                   //
///////////////////////////////////////////////////////////////////////
`include "src/defines.v"
module ieee_adder(add_sub_bit,inputA,inputB,clock_in,outputC)
	input  add_sub_bit;
	input `TYPE_NUMBER inputA;
	input `TYPE_NUMBER inputB;
	input  clock_in;
	output `TYPE_NUMBER outputC;
endmodule
